tengutower/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path('admin/', admin.site.urls),
    path('wifi/', include('wifi.urls')),

    # Static files
    # path('about/', views.about, name="about"),
    # path('new-project/', views.new, name="new"),
]

wifi/urls.py
from django.urls import path
from . import views

app_name = 'wifi'
urlpatterns = [
    path('', views.index, name="index"),
    path('<int:wifiid>/', views.details, name="details"),
    path('<int:wifiid>/edit', views.edit, name="edit"),
    path('<int:wifiid>/delete', views.delete, name="delete"),
    path('about/', views.about, name="about"),
    path('new/', views.new, name="new",)
]

wifi/models.py
from django.db import models
from django.conf import settings


class CommonFields(models.Model):
    # author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        abstract = True


# activestat: active, inactive
# structure: hotel, restaurant, home, event, etc.
# location: BGC, Baguio
class Taxonomy(CommonFields):
    taxread = models.CharField(max_length=50)
    taxvalue = models.CharField(max_length=50)
    taxtype = models.CharField(max_length=20)
    is_active = models.BooleanField(default=True, verbose_name='Activate now')

    def __str__(self):
        return "{} ({})".format(self.taxread, self.taxtype)


# status: activestat
# location: location
class Establishment(CommonFields):
    establishment = models.CharField(max_length=50)
    location = models.ForeignKey(Taxonomy, on_delete=models.CASCADE, related_name="estloc")
    status = models.ForeignKey(Taxonomy, on_delete=models.CASCADE, related_name="eststat")

    def __str__(self):
        return self.loc


class Address(CommonFields):
    establishment = models.ForeignKey(Establishment, on_delete=models.CASCADE)
    opentime = models.DateTimeField(null=True)
    closetime = models.DateTimeField(null=True)
    city = models.CharField(max_length=100, blank=True)
    country = models.CharField(max_length=100, blank=True)


class Owner(CommonFields):
    first_name = models.CharField(max_length=191)
    last_name = models.CharField(max_length=191)

    def __str__(self):
        return "{} {}".format(self.first_name, self.last_name)


# wifistat: active
# wifistr: structure
class Wifi(CommonFields):
    title = models.CharField(max_length=50)
    ssid = models.CharField(max_length=50)
    passwd = models.CharField(max_length=50)
    wpspin = models.CharField(max_length=20, null=True, blank=True)
    notes = models.CharField(max_length=191, null=True, blank=True)
    encryption = models.ForeignKey(Taxonomy, on_delete=models.CASCADE, related_name="wifienc", null=True, blank=True)
    structure = models.ForeignKey(Taxonomy, on_delete=models.CASCADE, related_name="wifistr", null=True, blank=True)
    status = models.ForeignKey(Taxonomy, on_delete=models.CASCADE, related_name="wifistat", null=True, blank=True)
    is_hacked = models.BooleanField(default=False)
    is_mobile = models.BooleanField(default=False)
    is_router = models.BooleanField(default=True)

    def __str__(self):
        return "{}".format(self.ssid)


# projstat: noted, planning, development, active, inactive
class Project(CommonFields):
    project = models.CharField(max_length=191)
    description = models.TextField(null=True, blank=True)
    is_active = models.BooleanField(default=False)
    is_visible = models.BooleanField(default=True)
    # status = models.ForeignKey(Taxonomy, on_delete=models.CASCADE, related_name="projstat")

    def __str__(self):
        return self.project

wifi/forms.py
from django import forms


class WifiForm(forms.Form):
    title = forms.CharField(max_length=50, required=False)
    ssid = forms.CharField(max_length=50)
    password = forms.CharField(max_length=50, widget=forms.PasswordInput)
    # wpspin = forms.CharField(max_length=20)
    notes = forms.CharField(max_length=191)
    # encryption = forms.ForeignKey()
    # structure = forms.ForeignKey()
    # status = forms.ForeignKey()
    is_hacked = forms.BooleanField(widget=forms.CheckboxInput, required=False)
    # is_mobile = forms.BooleanField()
    # is_router = forms.BooleanField()

tengutower/views.py
# from django.http import HttpResponse
from django.shortcuts import render


def index(request):
    context = {
        'page_title': 'Global Index',
    }
    return render(request, 'index.html', context)

wifi/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .forms import WifiForm
from .models import Wifi

def index(request):
    context = {
        'page_title': 'Wifi Index'
    }
    return render(request, 'wifi/index.html', context)


def new(request):
    if request.method == 'POST':
        form = WifiForm(request.POST)

        if form.is_valid():
            # Init
            title = form.cleaned_data['title']
            ssid = form.cleaned_data['ssid']
            password = form.cleaned_data['password']
            notes = form.cleaned_data['notes']
            is_hacked = form.cleaned_data['is_hacked']

            data = Wifi(title=title, ssid=ssid, passwd=password, notes=notes, is_hacked=is_hacked)
            data.save()

            return HttpResponse('Success!')

    else:
        form = WifiForm()

    context = {
        'form': form
    }
    return render(request, 'wifi/new.html', context)


def details(request, wifiid):
    return HttpResponse('Details for {}'.format(wifiid));


def edit(request, wifiid):
    return HttpResponse('Edit wifi {}'.format(wifiid));


def delete(request, wifiid):
    return HttpResponse('Delete wifi {}'.format(wifiid));


def about(request):
    return HttpResponse('Static: About Wifi');

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

    <title>{{ page_title }}</title>

    <link rel="stylesheet" type="text/css" href="{% static 'global.css' %}">
    {% block style %}{% endblock %}
    
</head>
<body>

    <div>
        {% block navbar %}
            <nav id="navbar">
                <div class="nav-wrapper">
                    <a href="#" class="brand-logo">Tengu Tower</a>
                    <ul id="nav-mobile" class="right hide-on-med-and-down">
                        <li><a href="about.html">About this project</a></li>
                        <li><a href="addproject.html" class="btn waves-effect">Add Project</a></li>
                    </ul>
                </div>
            </nav>
        {% endblock %}
    </div>


    {% block breadcrumbs %}{% endblock %}

    <div id="wrapper">
        {% block content %}
            <p>Your data goes here</p>
        {% endblock %}
    </div>

    <footer id="footer">
        <div class="top">
            {% block footer %}
                Footer here
            {% endblock %}
        </div>
        <div class="bottom">
            <div id="copyright">
                Copyright {% now "Y" %}. All Rights Reserved
            </div>
        </div>
    </footer>


    <script type="text/javascript" src="{% static 'js/bin/materialize.min.js' %}"></script>

</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <div id="content">
        
        <header>
            <h1>Projects</h1>
        </header>        

        <main id="body">
            

            <table width="100%" cellpadding="0" cellspacing="0" class="striped project-list">
                <thead>
                    <tr>
                        <th scope="col">Project</th>
                        <th scope="col">Active</th>
                        <th scope="col">Description</th>
                    </tr>
                </thead>

                <tbody>
                    <tr>
                        <td><a href="{% url 'wifi:index' %}">Wifi Manager</a></td>
                        <td class="active">Yes</td>
                        <td>Log of all wifi networks you've ever used</td>
                    </tr>
                    <tr>
                        <td>DVD</td>
                        <td class="active">No</td>
                        <td>Find which DVD each movie is in</td>
                    </tr>
                    <tr>
                        <td>Random Notes</td>
                        <td class="active">No</td>
                        <td>Just random note taking</td>
                    </tr>
                    <tr>
                        <td>Scanned Image Uploader</td>
                        <td class="active">No</td>
                        <td>Collate all your scanned images and tag them</td>
                    </tr>
                    <tr>
                        <td>Pobear</td>
                        <td class="active">No</td>
                        <td>Management of all your POs</td>
                    </tr>
                </tbody>

            </table>

        </main>

    </div>

{% endblock %}

wifi/templates/wifi/index.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
    <link rel="stylesheet" type="text/css" href="{% static 'wifi/style.css' %}">
{% endblock %}

{% block navbar %}
    <nav id="navbar">
        <div class="nav-wrapper">
            <a href="#" class="brand-logo">Wifi Management</a>
            <ul id="nav-mobile" class="right hide-on-med-and-down">
                <li><a href="{% url 'wifi:index' %}">View all records</a></li>
                <li><a href="{% url 'wifi:about' %}">About this app</a></li>
                <li><a href="{% url 'wifi:new' %}" class="btn waves-effect">Add New Wifi</a></li>
            </ul>
        </div>
    </nav>
{% endblock %}

{% block breadcrumbs %}
    <div id="breadcrumbs">
        <div class="nav-wrapper">
            <a href="{% url 'index' %}">&laquo; Back to Projects</a>
        </div>
    </div>
{% endblock %}

{% block content %}
    
    <div id="content">
        <header>
            <h1>Wifi List</h1>
        </header>        

        <main id="body">
            <table width="100%" cellpadding="0" cellspacing="0" class="striped project-list">
                <thead>
                    <tr>
                        <th scope="col">SSID</th>
                        <th scope="col">Password</th>
                        <th scope="col">Establishment</th>
                    </tr>
                </thead>

                <tbody>
                    <tr>
                        <td><a href="{% url 'wifi:index' %}">Wifi Manager</a></td>
                        <td class="active">Yes</td>
                        <td>Log of all Wifi you've ever used</td>
                    </tr>
                </tbody>
            </table>
        </main>
    </div>

{% endblock %}

wifi/templates/wifi/new.html
{% extends 'wifi/index.html' %}
{% load static %}
{% load widget_tweaks %}

{% block style %}
    <link rel="stylesheet" type="text/css" href="{% static 'wifi/style.css' %}">
{% endblock %}


{% block content %}
    
    <div id="content">
        
        <header>
            <h1>New Wifi</h1>
        </header>        

        <main id="body" class="form">

            <form action="{% url 'wifi:new' %}" method="post">
                {% csrf_token %}
                <ul class="nolist">
                    <li>
                        <div class="input-field field-wrapper">
                            {{ form.title.errors }}
                            {{ form.title }}
                            <label for="{{ form.title.id_for_label }}">Title</label>
                        </div>
                    </li>
                    <li>
                        <div class="input-field field-wrapper">
                            {{ form.ssid.errors }}
                            {{ form.ssid }}
                            <label for="{{ form.ssid.id_for_label }}">SSID</label>
                        </div>
                    </li>
                    <li>
                        <div class="input-field field-wrapper">
                            {{ form.password.errors }}
                            {{ form.password }}
                            <label for="{{ form.password.id_for_label }}">Password</label>
                        </div>
                    </li>
                    <li>
                        <div class="input-field field-wrapper">
                            {{ form.notes.errors }}
                            {% render_field form.notes %}
                            <label for="{{ form.notes.id_for_label }}">Notes</label>
                        </div>
                    </li>
                    <li>
                        <div class="input-field field-wrapper">
                            {{ form.is_hacked.errors }}
                            <label for="{{ form.is_hacked.id_for_label }}">
                                {% render_field form.is_hacked class="filled-in" %}
                                <span>Peeked</span>
                            </label>
                        </div>
                    </li>
                </ul>

                <div class="submit right-align"><input type="submit" value="Add Wifi" class="btn waves-effect" /></div>
            </form>

        </main>

    </div>

{% endblock %}